# http://www.stuartellis.eu/articles/rake/#rake-filehandling

require "open-uri"
require "fileutils"

require "rake/clean"
require "prawn"

CLEAN.include("images/*", "data/mood-logs.csv")

task "download-logs" do
  data = open(ENV["MOOD_LOG_URL"])

  File.open("data/mood-logs.csv", "w") do |file|
    IO.copy_stream(data, file)
  end
end

task "generate-plots" => "download-logs" do
  %w[frequency.R work-rest.R day-of-week.R 
     weighted-summary.R daily-average.R].each { |script| sh %{Rscript #{script}} }
end

task "generate-report" => "generate-plots" do
  rm_f "report.pdf"

  plots = %w[daily-average weighted-average-summary
             work-average rest-average day-of-week-summary
             frequency1 frequency2 frequency3 frequency4 frequency5]

  Prawn::Document.generate("report.pdf") do
    plots.each do |plot| 
      image "images/#{plot}.jpg", :position => :center, :scale => 0.5 
    end
  end

  Rake::Task["clean"].invoke
end

task :default => "generate-report"
