# http://www.stuartellis.eu/articles/rake/#rake-filehandling

require "open-uri"
require "fileutils"

require "rake/clean"
require "prawn"

CLEAN.include("images/*", "data/mood-logs.csv")

task "download-logs" do
  data = open(ENV["MOOD_LOG_URL"])

  File.open("data/mood-logs.csv", "w") do |file|
    IO.copy_stream(data, file)
  end
end

task "generate-plots" => "download-logs" do
  %w[frequency.R work-rest.R day-of-week.R 
     weighted-summary.R daily-min-max.R].each { |script| sh %{Rscript #{script}} }
end

task "generate-report" => "generate-plots" do
  rm_f "report.pdf"

  Prawn.debug = true



  Prawn::Document.generate("report.pdf", :page_layout => :landscape) do
    draw_image = ->(file, params={}) { image "images/#{file}.jpg", 
                                       {:scale => 0.42}.merge(params) }


    float { draw_image.("weighted-average-summary", :position => :left) }
    draw_image.("daily-min-max", :position => :right)

    move_down 20

    draw_image.("day-of-week-summary", :position => :center)

    start_new_page

    move_down 20


    text "Mood rating frequency by time", :align => :center
    move_down 30

    (1..5).each do |i|
      float do
        image "images/frequency#{i}.jpg", :position => (i-1)*(bounds.width / 5), :scale => 0.20
      end
    end

    move_down 200

    float { draw_image.("work-average", :position => :left) }
    draw_image.("rest-average", :position => :right)
  end

  Rake::Task["clean"].invoke
end

task :default => "generate-report"
