VAGRANTFILE_API_VERSION="2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-12.04"

  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/"+
                      "precise-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network :private_network, ip: "10.10.10.10"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 768]
    v.customize ["modifyvm", :id, "--cpus", 1]
  end

  config.omnibus.chef_version = "11.6.2"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "vendor/cookbooks"
 
    # Specify the recipe to run
    chef.json = { "run_list" =>  ["recipe[demo::default]"] }
  end
end
